[project]
name = "dotcor-backend"
version = "0.0.1"
description = "Backend for dotcor"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.139.2",
    "psycopg2-binary>=2.9.12",
    "psycopg2[binary]>=2.9.12",
    "pydantic-settings>=2.14.2",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.51.0",
]
