[project]
name = "dotcor-backend"
version = "0.0.1"
description = "Backend for dotcor"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.139.2",
    "uvicorn>=0.51.0",
    "sqlalchemy>=2.0.51",
    "psycopg2-binary>=2.9.12",
    "pwdlib[argon2]>=0.3.0",
    "pydantic[email]>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pydantic-extra-types[phonenumbers]>=2.11.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "httpx2>=2.12.0",
    "locust>=2.46.3",
]

[tool.pytest.ini_options]
pythonpath = "."
